version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: .aws/scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: .aws/scripts/start.sh
      runas: ubuntu
  ValidateService:
    - location: .aws/scripts/healthcheck.sh
      runas: ubuntu
permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu
