version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing production packages
      - apt install build-essential -y
      - yarn install
      - echo Decrypting ENV
      - yarn quickcert decrypt -k $CERT_ENV
      # - bash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"
      - export CODEBUILD_GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - if [ "$CODEBUILD_GIT_BRANCH" = "" ] ; then export CODEBUILD_GIT_BRANCH="$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')"; fi
      - echo "$CODEBUILD_GIT_BRANCH"
      - if [ "$CODEBUILD_GIT_BRANCH" = "master" ] ; then mv .aws/appspec.yml ./appspec.yml; else mv .aws/appspec-dev.yml ./appspec.yml; fi
  pre_build:
    commands:
      - yarn test-auto
  build:
    commands:
      - echo Build stating on `date`
      - yarn build
  post_build:
    commands:
      - echo Nothing to do in post_build...
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'
