version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing production packages
      - npm install
      - echo Decrypting ENV
      - npm run dec:env
  pre_build:
    commands:
      - npx jest --detectOpenHandles --forceExit --testTimeout=10000
  build:
    commands:
      - echo Build stating on `date`
      - npm run build
  post_build:
    commands:
      - echo Nothing to do in post_build...
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'
