version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing production packages
      - apt install build-essential -y
      - yarn install
      - echo Decrypting ENV
      - npm run dec:env
      - bash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"
      - if [ $CODEBUILD_GIT_BRANCH = master ] ; then mv .aws/appspec.yml ./appspec.yml; else mv .aws/appspec-dev.yml ./appspec.yml; fi
      - mv .aws/appspec.yml .
  pre_build:
    commands:
      - npx jest --detectOpenHandles --forceExit --testTimeout=10000
  build:
    commands:
      - echo Build stating on `date`
      - npm run build
  post_build:
    commands:
      - echo Nothing to do in post_build...
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'
